NVIDIA/cub

cub/agent/agent_histogram.cuh

Previously, when passing in an, e.g. CountingInputIterator, the kernel
would fail with the error:
======== Invalid __global__ read of size 4
=========     by thread (0,0,0) in block (0,0,0)
=========     Address 0x00000000 is out of bounds
because the wrong branch tried to read from d_native_samples (which is null).

Fix DeviceHistogram bug: non-native input iterators take the correct code path.

---

cub/util_allocator.cuh

I believe there is a race condition on the CUDA event between `DeviceFree()` and `DeviceAllocate()`.
Now the mutex is unlocked after the freed memory block is inserted in the free list (`cached_blocks`), but before the `cudaEventRecord()`. Then there is a short period of time when the memory block is in the free list, and the status of the CUDA event is not yet `cudaErrorNotReady`, and thus the `DeviceAllocate()` (called in another thread) may consider that memory block to be free to be used for another CUDA stream in
https://github.com/NVlabs/cub/blob/c3cceac115c072fb63df1836ff46d8c60d9eb304/cub/util_allocator.cuh#L408-L409
This PR suggests to fix the race condition by recording the CUDA event while still holding the mutex in `DeviceFree()`.

Fix a race for the CUDA event between DeviceFree() and DeviceAllocate() in the allocator

---

cub/agent/agent_scan.cuh
cub/device/device_scan.cuh
cub/device/dispatch/dispatch_scan.cuh
test/test_device_scan.cu

https://wg21.link/P0571
Continuation of brycelelbach/cub_historical_2019_2020#52.
DVS CL 29098336

Update the scan implementation to follow P0571's guidance.

---

CMakeLists.txt
cmake/CubAddSubdir.cmake
examples/CMakeLists.txt
examples/cmake/CMakeLists.txt
examples/cmake/add_subdir/CMakeLists.txt
examples/cmake/add_subdir/dummy.cu

Continuation of the PR at brycelelbach/cub_historical_2019_2020#59.

Add support for importing CUB targets with add_subdirectory.

---

cub/util_allocator.cuh

Fixed a call to `CubDebug` in `CachingDeviceAllocator::DeviceAllocate`, where `CubDebug` was called on the return value of the `==` operator instead of the CUDA runtime API call.

Fixed CubDebug usage in CachingDeviceAllocator::DeviceAllocate

---

cub/agent/agent_scan.cuh
cub/device/dispatch/dispatch_scan.cuh

Thrust will be switching to `cub::DeviceScan` to replace its custom scan
implementation. This patch addresses some issues found by the Thrust
tests:
- Initialize unused `BlockLoad` items with values known to be in the input
set. This fixes the `TestInclusiveScanWithIndirection` Thrust test by
keeping the `plus_mod3` functor indices valid.
- Use `OffsetT` instead of `int` to hold indicies in `AgentScan`. This
fixes the `Test*ScanWithBigIndexes` Thrust tests by not truncating
the input problem size.
- Use `BLOCK_[STORE|LOAD]_WARP_TRANSPOSED_TIMESLICED` instead of
`BLOCK_[STORE|LOAD]_WARP_TRANSPOSED` when the intermediate type is
larger than 128 bytes. This keeps shared memory buffers from growing
too large in the `TestScanWithLargeTypes` Thrust test.

Update DeviceScan to pass Thrust's scan tests

---

cub/agent/agent_radix_sort_upsweep.cuh
cub/agent/agent_reduce.cuh
cub/block/block_load.cuh
cub/block/block_radix_rank.cuh
cub/block/block_store.cuh
cub/block/specializations/block_reduce_raking.cuh
cub/block/specializations/block_scan_raking.cuh
cub/device/dispatch/dispatch_radix_sort.cuh
cub/util_type.cuh

Various warnings are triggered using clang-10 with the flag `-Wdeprecated-anon-enum-enum-conversion`.  This PR proposes to suppress those warnings by casting to `int`

workarounds for clang-10 warnings

---

cub/util_namespace.cuh

Fixes #222 
Verified using the following example from issue #222 
```
#define CUB_NS_PREFIX namespace {
#define CUB_NS_POSTFIX }
#include <cub/cub.cuh>
int main()
{
int res = (int)cub::Equals<int, int>::VALUE;
return res;
}
```

Fix to support wrapping CUB in a custom outer namespace with macros

---

cub/agent/agent_reduce_by_key.cuh
cub/agent/agent_scan.cuh
cub/agent/agent_segment_fixup.cuh

A few remaining ints changed to OffsetT. This allows us to switch cub to use 64 bit offsets via  `cub::DispatchScan` without crashing.
Related: https://github.com/dmlc/xgboost/pull/6234

Fix some integer overflows

---

cub/util_arch.cuh
cub/util_type.cuh
test/test_device_radix_sort.cu

This fixes the problem with CUB using deprecated shfl/vote instructions when CUB
is compiled with clang (e.g. some TensorFlow builds).

Fix CUDA version detection in CUB

---

cub/util_device.cuh

avoids clang -Wparentheses warning: using the result of an assignment as a condition, resolves #219

avoids clang -Wparentheses warning

---

cub/util_type.cuh
test/test_device_radix_sort.cu

A recent commit changed several occurances of `__CUDACC_VER_MAJOR__ >= 9` in preprocessor expressions to `(__CUDACC_VER_MAJOR__ >= 9 || CUDA_VERSION >= 9000)`.  NVC++ defines `CUDA_VERSION` but not `__CUDACC_VER_MAJOR__`, so the commit changed the condition from false to true for NVC++.  The code inside those blocks doesn't work with NVC++, causing compilation errors.  Fix the regression by changing the expressions to `(__CUDACC_VER_MAJOR__ >= 9 || CUDA_VERSION >= 9000) && !__NVCOMPILER_CUDA__`.

Fix cub/util_type.cuh to not use 16-bit float with NVC++

---

CMakeLists.txt
cmake/CubCompilerHacks.cmake
cmake/CubCudaConfig.cmake
cmake/CubInstallRules.cmake
cub/cmake/cub-config-version.cmake
cub/cmake/cub-config.cmake
test/CMakeLists.txt
test/cmake/CMakeLists.txt
test/cmake/test_install/CMakeLists.txt

See https://github.com/nvidia/thrust/issues/1322
Updates the cmake install rules to install in `lib/cub/cmake` instead of `include/cub/cmake` as the include folder is not searched in a normal `find_package(cub)` call.

Update install rules to install cmake into lib directory

---

cub/device/dispatch/dispatch_radix_sort.cuh

The new tuning parameters for radix sort are causing a performance
regression (2MiB input, 16-bit keys, GV100, 21.62 -> 16.01 GiB/sec).
See referenced NVBug for details.
Bug 200676467

Fix radix sort perf regression.

---

test/test_device_histogram.cu

The code has been broken forever, we don't need it, and NVHPC doesn't have NPP, so it fails to build this test when `npp.h` is not found.

Remove NPP dependency from `test_device_histogram.cu`. 

---

cub/agent/agent_radix_sort_downsweep.cuh
cub/agent/agent_radix_sort_histogram.cuh
cub/agent/agent_radix_sort_onesweep.cuh
cub/agent/agent_radix_sort_upsweep.cuh
cub/block/block_radix_rank.cuh
cub/block/block_radix_sort.cuh
cub/block/radix_rank_sort_operations.cuh
cub/device/device_radix_sort.cuh
cub/device/device_segmented_radix_sort.cuh
test/test_block_radix_sort.cu
test/test_device_radix_sort.cu
test/test_util.h

This modifies digit extraction in radix sorting to sort -0.0 and +0.0 in stable order.

Stable sorting order for -0.0 and +0.0 for float and double.

---

cub/device/dispatch/dispatch_radix_sort.cuh

This suppresses "warning: conditional expression between different enumeration types" in clang.

suppresses newly triggered warnings in clang

---

cub/cmake/cub-config-version.cmake

This prevents an internal variable from appearing in CMake's UIs when
our CMake package is used.

Mark CMake var as internal.

---

cub/device/dispatch/dispatch_radix_sort.cuh

I observed a problem in my code when trying to use DeviceRadixSort::SortPairs with num_items >= 2^32, despite correct instatiation of template ```cub::DispatchRadixSort<false, KeyType, ValueType, IndexType>::Dispatch```
With ```num_items = 4333734380ull``` results were incorrect, ```num_items = std::numeric_limits<std::uint32_t>::max()``` caused a crash.
The reason is that InitPassConfig uses ```int``` for the number of items, instead of provided OffsetT. This is fixed by this commit.
I used the following test code. It requires approx 140GB of device (managed) memory.
```
#include <iostream>
#include <algorithm>
#include <fstream>
#include <cassert>
#include <vector>
#include <numeric>
#include <limits>
#include <cub/cub.cuh>
__global__
void initKernel(
std::uint64_t* keys,
std::uint64_t* …
```

Use data type OffsetT for DispatchRadixSort correctly in InitPassConfig

---

cub/util_device.cuh

These functions started producing invalid results in CUDA 11 under
certain circumstances (see issue NVIDIA/thrust#1371), and removing
these hints fixes the issue.
cc: @ArEsKay3
Fixes NVIDIA/thrust#1371

Remove some problematic inline annotations.

---

CMakeLists.txt
cmake/CubBuildTargetList.cmake

On by default. When disabled:
a) Emit configuration error if more than one dialect option is enabled, and
b) Remove dialect information from target / executable names.
Fixes NVIDIA/cub#250.

Add CUB_ENABLE_CPP_DIALECT_IN_NAMES CMake flag

---

cub/util_device.cuh

Emergency fix to regression blocking internal builds (NVBug 3255833).
Verified manually on GCC 7.5 and MSVC 2019.

Replace removed __forceinline__s with regular inlines.

---

cub/util_compiler.cuh

In the near future, `nvc++ -stdpar` will be changed to no longer predefine the macro `__CUDACC__`.  Adjust the uses of `__CUDACC__` in Thrust and CUB to check for NVC++'s stdpar mode in addition to the `__CUDACC__`.

nvc++ and __CUDACC__

---

cub/util_cpp_dialect.cuh

This is going into the `1.12.X` side branch for the CTK-11.4-specific `CUB 1.12.1` release.

[NVBug 3308316] Update deprecation messages for CTK 11.4.

---

cub/device/device_segmented_radix_sort.cuh
cub/device/device_segmented_reduce.cuh
cub/device/dispatch/dispatch_radix_sort.cuh
cub/device/dispatch/dispatch_reduce.cuh
test/test_device_radix_sort.cu
test/test_device_reduce.cu

Modified segmented reduce, segmented radix sort and their tests.

Allow segmented problems to have different types for offset iterators.

---

.gitignore
CONTRIBUTING.md
README.md

The building instruction in README.md doesn't work. Without cloning thrust, nvcc will try to use CUDA's built-in thrust, which will error with version not match.

Fix instructions on building cub

---

cub/device/device_histogram.cuh

When using gcc=7.5.0 and `OffsetT=int64_t`, the following template errors occur:
```
/usr/local/cuda/include/cub/device/device_histogram.cuh(144): error: no instance of overloaded function "dgl::cub::DeviceHistogram::MultiHistogramEven" matches the argument list
argument types are: (void *, size_t, int32_t *, unsigned long long *[1], int [1], int32_t [1], int32_t [1], int64_t, int, unsigned long, cudaStream_t, __nv_bool)
detected during:
instantiation of "cudaError_t dgl::cub::DeviceHistogram::HistogramEven(void *, size_t &, SampleIteratorT, CounterT *, int, LevelT, LevelT, OffsetT, cudaStream_t, __nv_bool) [with SampleIteratorT=int32_t *, CounterT=unsigned long long, LevelT=int32_t, OffsetT=int64_t]"
```
This resolves this, by casting the `0` to an `OffsetT`, so as to ensure `num_rows` …

Fix cub::DeviceHistogram::MultiHistogramEven() 1-Dimensional overload, when OffsetT is not an `int`.

---

cub/device/device_scan.cuh
test/test_device_scan.cu

Per the title. PyTorch is already using this assumption, and it seems to be working fine. But we want the support of this feature to be official.
cc: @ngimel

Document that cub's device scan supports inplace operations, and add tests to enforce this feature.

---

cub/block/block_radix_sort.cuh
cub/device/device_radix_sort.cuh
cub/device/device_segmented_radix_sort.cuh

Fixes #282, extends and replaces #284.

Radix sort stability docs

---

cmake/CubCudaConfig.cmake
cub/block/block_shuffle.cuh
test/test_block_shuffle.cu

In order to fix [the issue](https://github.com/NVIDIA/cub/issues/264) with `BlockShuffle::Down` function I've written tests for `BlockShuffle` . It turned out that it was broken because of the wrong `_TempStorage` type which also led to extra shared memory usage.

Fix block shuffle

---

cub/block/block_store.cuh

WARP_TIME_SLICING is contained in ALGORITHM and shouldn't be listed as a standalone template parameter.
Signed-off-by: Peter Han <fujun.han@iluvatar.ai>

Remove WARP_TIME_SLICING template param desc.

---

cub/block/block_load.cuh
cub/block/block_store.cuh
test/test_block_load_store.cu

This PR adds the following to `BlockLoadAlgorithm`
1. BLOCK_LOAD_STRIPED
It's basically BLOCK_LOAD_TRANSPOSE without the BlockExchange
This PR adds the following to `BlockStoreAlgorithm`
1. BLOCK_STORE_STRIPED
It's basically BLOCK_STORE_TRANSPOSE without the BlockExchange

Add BLOCK_LOAD_STRIPED and BLOCK_STORE_STRIPED

---

README.md

Fixing broken hyperlinks since subdomains of github.com are deprecated for GitHub Pages.

Subdomains of github.com are deprecated for GitHub Pages

---

cub/block/block_discontinuity.cuh

Fix [the issue](https://github.com/NVIDIA/cub/issues/314) about out-of-boundary access in the `BlockDiscontinuity::FlagHeadsAndTails` method.

Fix OOB access in FlagHeadsAndTails

---

cub/device/dispatch/dispatch_radix_sort.cuh

Fixed sanitizer warnings in `RadixSortScanBinsKernel`.
- correct per-pass spine length
- correctly handling the last scan tile
- fixes warnings from https://github.com/NVIDIA/thrust/issues/1400

Fixed sanitizer warnings in RadixSortScanBinsKernel

---

cub/util_allocator.cuh

This PR fixes the following issues
1.
The following code prints correct number of cached bytes, but incorrect number of cached blocks. 
```#include <cub/cub.cuh>
int main(){
cub::CachingDeviceAllocator alloc(
false, //skip_cleanup 
true //debug
);
void* ptr;
alloc.DeviceAllocate(&ptr, 128);
alloc.DeviceFree(ptr);
alloc.FreeAllCached();
}
```
```
Device 0 allocated new device block at 0x7fffca400000 (512 bytes associated with stream 0).
0 available blocks cached (0 bytes), 1 live blocks outstanding(512 bytes).
Device 0 returned 512 bytes from associated stream 0.
1 available blocks cached (512 bytes), 0 live blocks outstanding. (0 bytes)
Device 0 freed 512 bytes.
1 available blocks cached (0 bytes), 0 live blocks (0 bytes) outstanding.
```
2.
Mutex remains locked in DeviceFree if error …

Small fixes for CachingDeviceAllocator

---

cub/block/radix_rank_sort_operations.cuh

This will fix https://github.com/NVIDIA/cub/issues/334

Fix clang compile error

---

cub/block/radix_rank_sort_operations.cuh

NVC++ warns about unreachable code in specializations of `BaseDigitExtractor::ProcessFloatMinusZero` where `FLOAT_KEY` is false.  Rearrange the code to avoid the warning, without changing the behavior at all.

Avoid warnings about unreachable code

---

cub/agent/agent_merge_sort.cuh
cub/block/block_load.cuh
cub/block/block_merge_sort.cuh
cub/block/block_store.cuh
cub/cub.cuh
cub/device/device_merge_sort.cuh
cub/device/dispatch/dispatch_merge_sort.cuh
cub/util_macro.cuh
cub/util_math.cuh
test/test_block_merge_sort.cu
test/test_device_merge_sort.cu
test/test_util.h

This PR contains a port of thrust merge sort algorithm, which was split into device and block parts.

Add CUB block and device merge sort

---

cub/device/dispatch/dispatch_spmv_orig.cuh
cub/iterator/tex_obj_input_iterator.cuh
cub/iterator/tex_ref_input_iterator.cuh
experimental/spmv_compare.cu

Fixes Issues #161 and #162

---

cub/device/device_histogram.cuh

- Remove extra values from `d_histogram` result.
- Update input samples to avoid fp values that are the same as
a computed level. These introduce ambiguity into the result due
to fp rounding/math.
cc: @cliffburdick

Update histogram documentation.

---

cub/agent/agent_spmv_orig.cuh
cub/device/device_spmv.cuh
cub/device/dispatch/dispatch_spmv_orig.cuh
cub/iterator/tex_obj_input_iterator.cuh
test/test_device_spmv.cu
test/test_util.h

Fixes #139 and #285. Includes #160.
This is blocking #276, since we need tests to validate the if-target update for `DeviceSpmv`.

cub::DeviceSpmv: Various fixes and tests

---

cub/block/block_discontinuity.cuh
cub/block/block_exchange.cuh
cub/block/block_histogram.cuh
cub/block/block_load.cuh
cub/block/block_merge_sort.cuh
cub/block/block_radix_rank.cuh
cub/block/block_radix_sort.cuh
cub/block/block_reduce.cuh
cub/block/block_scan.cuh
cub/block/block_store.cuh
examples/block/example_block_reduce.cu
examples/block/example_block_reduce_dyn_smem.cu

As mentioned in https://github.com/NVIDIA/cub/issues/344, I created this PR to add a simple example of how to correctly use dynamic shared memory with `BlockReduce`.
I hope I followed the PR process correctly, I wasn't able to re-build the docs because the full build (for thrust) took longer than my allocated time on the machine when I was working on this, and I'm not familiar enough with the build process s.t. I can simply only build the docs for cub.
I'll amend the pull request, of course, if needed.
Plus, do you want me to add a similar example to classes like `BlockScan` ? In this case, it may be better to add an actual example file and link to it from the various inline docs.

Docs update: how to use dynamic shared mem with block reduce

---

CHANGELOG.md
README.md

Thanks to everyone who contributed to CUB 1.14.0!
@fkallen
@jwyles
@MatthiasKohl
@senior-zero
@seunghwak
@zingdle
Please look over the release notes in this PR and let me know if you'd like me to change anything.

Add 1.14.0 changelog.

---

cub/agent/single_pass_scan_operators.cuh
cub/block/block_radix_rank.cuh

This is in reference to NVIDIA/thrust#1478, two changes added to add explicit conversion so far. Use this branch along with the Thrust branch bug/github/wconversion-1478

First checkpoint for Wconversions warning fixes

---

cub/device/dispatch/dispatch_merge_sort.cuh

This PR contains compilation time improvement for the common case when agents fit into default shared memory size (48 KB).

Optimize compilation time for the common case

---

test/test_util.h

#295 reported that the `device_reduce` and `device_scan` tests were
failing due to the accumulated fp error exceeding the current threshold
of 0.01%. They observed a relative error of slightly more, 0.0100725%.
This appears to be happening on nvc++, though I've not been able to repro
the failure on NV HPC 21.7.
They suggest an alternate method of computing the summation that provides
more accuracy, but unfortunately this approach is not suitable for testing
cases where `scan_op` is not `cub::Sum`.
Instead, let's just bump up the error threshold to 0.015%.

Increase floating point tolerance when validating results.

---

cub/util_type.cuh
test/bfloat16.h
test/half.h
test/test_device_radix_sort.cu
test/test_util.h

- tests where a sorted array is generated and then permuted
- this is much faster than sorting on host for large `num_items`
- using `size_t num_items` throughout the test, to prepare for 64-bit `num_items` in CUB radix sort

Permutation-based tests for sorting

---

cub/device/dispatch/dispatch_segmented_sort.cuh
test/test_device_segmented_sort.cu

This PR fixes #409: 
1. Host-side calls don't synchronize with the default stream.
2. Device-side calls synchronize stream before `group_sizes` usage.
I've also added a simple device-side launch test. In order to get it compiling, run CMake with
```
cmake -DCUB_ENABLE_TESTS_WITH_RDC=ON ...
```
and add `#define CUB_CDP` in the test_device_segmented_sort.cu.

Fix segmented sort device-side launch

---

cub/detail/device_synchronize.cuh
cub/detail/exec_check_disable.cuh

This patch adds the same guards around the pragma that we use in Thrust.
Bug 3453249

Only use nv_exec_check_disable on nvcc.

---

cub/agent/agent_adjacent_difference.cuh
cub/block/block_adjacent_difference.cuh
cub/block/block_discontinuity.cuh
cub/block/block_reduce.cuh
cub/block/block_scan.cuh
cub/cub.cuh
cub/detail/type_traits.cuh
cub/device/device_adjacent_difference.cuh
cub/device/dispatch/dispatch_adjacent_difference.cuh
cub/thread/thread_operators.cuh
test/test_block_adjacent_difference.cu
test/test_device_adjacent_difference.cu

The PR contains:
1. a port of `thrust::adjacent_difference` algorithm;
2. deprecation of `FlagHeads` and `FlagTails` methods from `BlockAdjacentDifference` structure;
3. fixed API for `BlockAdjacentDifference` along with documentation and tests.
Note that the PR is based on some of the features introduced in `MergeSort` porting.

Port adjacent difference into CUB

---

cub/util_device.cuh

Fix bad cast in util_device.

---

test/test_device_merge_sort.cu
test/test_device_segmented_sort.cu
test/test_device_three_way_partition.cu
test/test_thread_sort.cu
test/test_warp_exchange.cu

This PR is part of the if-target split, and adds some missing includes uncovered by NVIDIA/thrust#1572.
Also organized the includes and ran them through clang-format to sort/dedup them.

Add missing thrust headers after fixing header leak.

---

test/test_device_radix_sort.cu

Skip pre-sorted tests for extended types.
- for 4-byte keys, int is the basic type

Skip pre-sorted tests for extended types.

---

cmake/CubInstallRules.cmake
cub/cmake/cub-config-version.cmake
cub/cmake/cub-header-search.cmake
cub/cmake/cub-header-search.cmake.in

Needed to fix https://github.com/NVIDIA/thrust/issues/1541

Support user defined CMAKE_INSTALL_INCLUDEDIR values

---

cub/iterator/discard_output_iterator.cuh

Fixes #419 and gpuCI gcc10 builds.

Initialize padding member to silence warning.

---

test/half.h

Replace the type-punning with a UB-safe bit conversion. The
compiler will optimize the memcpy out and just convert the bits.

Fix spurious uninitialized variable warning on gcc11.

---

cmake/header_test.in
cub/device/dispatch/dispatch_segmented_sort.cuh

This PR fixes [the issue ](https://github.com/NVIDIA/cub/issues/422) related to device segmented sort compilation in the presence of windows.h header.

Fix segmented sort compilation in case of windows.h

---

test/test_device_radix_sort.cu

There was a case where we were testing `num_items = 0 && num_segments = 1`. The radix sort tests don't support this, which leads to out of bounds accesses in multiple places. Somehow this issue doesn't show itself on Linux. All tests of device radix sort were failing on Windows in a racy way.

Fix segfault in device radix sort tests

---

cub/agent/agent_radix_sort_histogram.cuh
cub/agent/agent_radix_sort_onesweep.cuh
cub/device/device_radix_sort.cuh
cub/device/dispatch/dispatch_radix_sort.cuh
test/test_device_radix_sort.cu

- 64-bit `OffsetT` is supported for onesweep sorting
- for decoupled look-back, the partition kernel is broken into smaller parts (as before), and a separate 32-bit type is used there
- for histograms, 32-bit counters are used in shared memory and `OffsetT`-sized counters in global memory

64-bit Offsets in DeviceRadixSort

---

examples/block/example_block_reduce_dyn_smem.cu

[The following PR](https://github.com/NVIDIA/cub/pull/348) introduces an example with unaligned memory accesses. This PR fixes this issue.

Fix alignment in dyn_smem example

---

cmake/header_test.in

Will need to be rebased / tested after NVIDIA/thrust#1548 is merged.

Update header tests to check for termios.h's B0 macro.

---

cub/device/device_spmv.cuh

These parameters are not exposed in the public APIs.
Fixes #416.

Remove references to alpha/beta from DeviceSpmv docs.

---

cub/device/dispatch/dispatch_adjacent_difference.cuh
cub/device/dispatch/dispatch_unique_by_key.cuh
cub/util_type.cuh

Fixes #435.
Will backport to 1.16.X and tag a new RC once merged.

Add missing <iterator> headers.

---

cub/agent/agent_select_if.cuh
cub/device/dispatch/dispatch_radix_sort.cuh
cub/device/dispatch/dispatch_select_if.cuh
test/test_device_radix_sort.cu
test/test_device_select_if.cu
test/test_device_select_unique.cu

During three-way partitioning development I've noticed that there's a bug in the select if implementation. It used output type to load data from input iterator. Recently, @elstehle brought the very same issue. Here's a code sample that fails to compile. This fact limits the applicability of the partitioning/selection facilities:
```cpp
#include <iostream>
#include <thrust/count.h>
#include <thrust/iterator/zip_iterator.h>
#include <thrust/iterator/transform_output_iterator.h>
#include <thrust/iterator/discard_iterator.h>
#include <thrust/device_vector.h>
#include <cub/device/device_select.cuh>
struct pair_to_col {
__host__ __device__ int operator()(const thrust::tuple<int, double> &in) {
return thrust::get<0>(in);
}
};
struct select {
__host__ __device__ bool operator()(const …
```

Fix select if for mixed types

---

cub/device/dispatch/dispatch_segmented_sort.cuh

This PR eliminates the device-side usage of the `cudaDeviceSynchronize` function which was depricated in the CUDA Toolkit 11.6. Since in the #409 @fkallen reported usage of the segmented soft in the CDP mode, it whould be great if @fkallen could verify the changes.

Eliminate device synchronization in CDP version of segmented sort

---

cub/device/dispatch/dispatch_segmented_sort.cuh
test/test_device_segmented_sort.cu

This is a backport of #445. Apart from the content of #445, this PR additionally backports the CDP test for validation purposes.

Eliminate device synchronization in CDP version of segmented sort (backport)

---

cub/device/dispatch/dispatch_segmented_sort.cuh

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/461).

Fix segmented sort for SM{61,70}

---

cub/block/block_discontinuity.cuh

Fixes: https://github.com/NVIDIA/cub/issues/337

update Iterate (BlockDiscontinuity) to use pragma unroll

---

cub/block/block_adjacent_difference.cuh

As per https://github.com/NVIDIA/cub/pull/450#issuecomment-1087910659

pragma unroll in block_adjacent_difference::Iterate

---

cub/detail/choose_offset.cuh
cub/device/device_adjacent_difference.cuh
cub/device/device_radix_sort.cuh
test/test_device_adjacent_difference.cu

This PR is a preparation for addressing comments in the following [PR](https://github.com/NVIDIA/thrust/pull/1512).

Alternative approach to 64-bit indexing in adjacent difference

---

cub/block/block_adjacent_difference.cuh
cub/block/block_shuffle.cuh
cub/device/device_partition.cuh
cub/device/device_scan.cuh
cub/util_device.cuh
cub/version.cuh
cub/warp/warp_load.cuh

Fix doxygen warnings while working on updating documentation https://github.com/NVlabs/cub/pull/1
fixes few missing documentations and typos.

fix doxygen warnings

---

cub/agent/agent_adjacent_difference.cuh
cub/device/device_adjacent_difference.cuh
cub/device/dispatch/dispatch_adjacent_difference.cuh

In continuation of the following [discussion](https://github.com/NVIDIA/thrust/pull/1512#discussion_r867071509), I've renamed the `InPlace` flag to `MayAlias`.

Better name for in-place flag in adj diff

---

cub/device/dispatch/dispatch_radix_sort.cuh

`debug_synchronous` support in Onesweep sort.
This should address https://github.com/NVIDIA/cub/issues/355.

debug_synchronous support in Onesweep sort

---

cub/agent/agent_scan_by_key.cuh

This fixes invalid memory accesses in two Thrust examples (`scan_by_key` and `summed_area_table`) on optimized nvc++ builds.

Wrap `AgentScanByKey::TempStorage` in `cub::Uninitialized`.

---

cub/agent/agent_scan_by_key.cuh
cub/device/device_scan.cuh
cub/device/dispatch/dispatch_scan.cuh
cub/device/dispatch/dispatch_scan_by_key.cuh
test/test_device_scan.cu
test/test_device_scan_by_key.cu

This PR addresses multiple issues of in-place execution for scan algorithms:
Scan:
- `LOAD_LDG` is removed from tuning policies to guarantee in-place execution. Affected architectures are Kepler and Maxwell. Benchmarks showed no difference in performance on those platforms. 
- In-place execution guarantees are highlighted in the documentation of the existing API
- In-place API is provided
- In-place tests are fixed. The code used to compare `decltype(*d_in)` with `OutputT` which always led to comparing `T&` with `T`. Therefore, we've never tested in-place execution. 
Scan by key:
- `LOAD_LDG` is removed from tuning policies to guarantee in-place execution. 
- To preserve thrust documentation guarantees, implementation is changed to allow aliasing of keys/results. This change affects …

In-place guarantees for scan algorithms

---

cub/device/dispatch/dispatch_adjacent_difference.cuh

This PR eliminates UB from adjacent difference for the case of in-place execution. Removing `LOAD_LDG` has performance implications, so I keep it for copy version of the API.

Fix in-place execution of adjacent difference

---

cub/device/device_histogram.cuh
test/test_device_histogram.cu

Histogram doesn't allow aliasing of the histogram and samples data. If `d_samples` is aliased with `d_histogram`, the algorithm will reset the aliased part of `d_samples` before reading it. If `d_levels` is aliased with `d_histogram`, the same will happen. Since levels and samples are readonly, it's safe to alias those.

Document in-place guarantees for histogram

---

cub/device/device_partition.cuh
test/test_device_select_if.cu

It's not allowed to alias in/out data in case of partition because unselected data might override input array for a CTA that hasn't been scheduled yet. These leads to loosing data.

In-place guarantees for partition

---

cub/device/device_run_length_encode.cuh

`Encode` doesn't allow aliasing for the same reason as reduce by key. `NonTrivialRuns` reads out-of-tile elements without synchronization. Aliasing in `NonTrivialRuns` would introduce data race.

In-place guarantees for rle

---

cmake/CubHeaderTesting.cmake
cmake/header_test.in
cub/util_type.cuh

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/478). I considered eliminating of `cuda_bf16.h` header inclusion, but it might lead to issues when algorithm header relies on some different header:
```cpp
#include <cub/util_type.cuh> // omitted bf16 specializations based on `__CUDA_BF16_TYPES_EXIST__`
#include <cuda_bf16.h> // defined `__CUDA_BF16_TYPES_EXIST__`
#include <cub/device/device_radix_sort.cuh> // expects bf16 specializations in `util_type.h` 
```
It seems to be safer to provide the disable macro that @leofang's suggested.

Add option to disable BF16 support

---

cub/device/device_select.cuh
cub/device/dispatch/dispatch_select_if.cuh
test/test_device_select_if.cu

Select algorithms are based on the decoupled look back approach. Therefore, subsequent thread blocks are guaranteed to write data strictly after input data was read. Unlike partition family, select writes data only from one side of the array. It's safe to have `in` iterator equal to the `out` one. The only issue is `LOAD_LDG` that is used by default. `LOAD_LDG` replacement with `LOAD_CA` leads to 50% slowdown on Kepler and about 30% slowdown on Maxwell. To avoid performance regression on these architectures I've forbidden in-place execution and left `LOAD_LDG`. Since it'd be unfortunate to loose in-place option, I introduced in-place overload that takes exactly one argument. This also addresses the following [issue](https://github.com/NVIDIA/cub/issues/502).
The unique subset of …

In place select

---

cub/agent/agent_adjacent_difference.cuh
cub/block/block_adjacent_difference.cuh
cub/device/dispatch/dispatch_adjacent_difference.cuh
test/test_block_adjacent_difference.cu
test/test_device_adjacent_difference.cu

This PR addresses two issues ([first](https://github.com/NVIDIA/cub/issues/506), [second](https://github.com/NVIDIA/cub/issues/507)). The copy version of the API didn't use to skip computation at the stage of temporary storage evaluation.

Fix temp storage allocation in adjacent difference copy

---

cub/device/device_reduce.cuh
cub/device/device_segmented_reduce.cuh

Reduce consists of two kernels. The first one reads input data and accumulates partial sums in a temporary storage. The second one reads the temporary storage and writes the final result. Therefore, it's safe to alias input and output arrays.
Nonetheless, allowing in-place execution would limit our abilities to optimize algorithm later. Since aliasing doesn't provide significant memory saving, I'd rather not allow it. 
Regarding `ByKey` variant, it relies on decoupled look back, so it should be safe to alias in/out data as long as value types for input/output iterators match exactly. The only limiting factor is `LOAD_LDG` which makes aliasing in this case an UB. In-place execution in this case would provide significant memory savings. If there's a request, I suggest we add an overload …

In-place guarantees for reduce

---

cub/device/device_radix_sort.cuh
cub/device/device_segmented_radix_sort.cuh
cub/device/device_segmented_sort.cuh

This PR clarified documentation on in-place guarantees for our sort facilities. I'll briefly mention the motivation behind these guarantees:
1. segmented sort: 
1.1. in/out: this overload allocates an intermediate storage so that input data is only read once. Nonetheless, sort facilities for small segments bypass this storage. This facilities use `LOAD_LDG`, which prohibits reading and writing into the same memory. Potentially, we might permit this overload to work in-place, but it'd take significant effort for re-tuning. It'd also create a false impression that the double buffer overload can alias data as well. I suggest we postpone this until there's a request. If there's one, we could create an overload that takes one set of values to emphasize in-place guarantees. 
1.2. double buffer: …

In-place guarantees for sort

---

cub/device/dispatch/dispatch_histogram.cuh
cub/thread/thread_search.cuh
test/half.h
test/test_device_histogram.cu

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/484). Since there's another histogram related PR, I've tried to keep changes to the dispatch layer minimalistic.

Support __half in histogram

---

cub/util_device.cuh

Fixes the regression described in #510.

Reapply changes from NVIDIA/cub#404 that were lost in conflict resolution.

---

cub/device/dispatch/dispatch_segmented_sort.cuh

Backport of the following [fix](https://github.com/NVIDIA/cub/pull/523) to 1.17 branch.

Fix device-side debug synchronous usage for seg sort

---

cmake/CubBuildCompilerTargets.cmake

Using managed memory breaks certain tests like `test_thread_sort` at least on windows / WSL
Disable it uniformly to be on the safe side and let the user deside whether they want the fast footgun

Disable managed memory for nvc++

---

cub/device/device_segmented_radix_sort.cuh
cub/device/device_segmented_sort.cuh
test/test_device_radix_sort.cu
test/test_device_segmented_sort.cu

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/485) by documenting segmented sort behaviour in case of unspecified ranges. It also adds tests to ensure this behaviour.

Document segmented sort behaviour for unspecified ranges

---

cub/util_debug.cuh

`cub::Debug` is used in most device algorithms and uses `cudaGetLastError` to reset errors occurred occurred during device-scope algorithms invocations. `cudaGetLastError` usage was introduced in 22b057306da72a353af837b5bfc887f036660486. The issue consists in `cudaGetLastError` usage in `__host__ __device__` functions in build with `-rdc=false`:
```cpp
__global__ void kernel() {
cudaGetLastError();
}
int main() {
kernel<<<1, 1>>>();
}
```
```bash
:nvcc main.cu
ptxas fatal   : Unresolved extern function 'cudaGetLastError'
```
The issue was caused by 3c20a56ded0029a7bf8800b783962df97a3abb10, so we have to backport this into 1.17. The fix consists in invoking `cudaGetLastError` only in the case of host invocations or device ones with `-rdc=true`.

Fix cub::Debug for builds without RDC

---

cub/warp/specializations/warp_reduce_shfl.cuh
cub/warp/warp_reduce.cuh
test/test_warp_reduce.cu

This PR fixes the [issue](https://github.com/NVIDIA/cub/issues/482) of single-threaded warp reduces. It also addresses the [issue](https://github.com/NVIDIA/cub/issues/279) which requested hardware acceleration for reductions on ampere.

Fix main/GitHub/warp reduce

---

cub/cmake/cub-header-search.cmake

When a consumer of cub uses the CMake `FIND_ROOT_PATH_MODE_INCLUDE` option it will cause all find_path searches to only occur under the find root path. Since this normally doesn't include the source files, it means that cub-header-search.cmake will fail to find the cub/version.cuh file.
This issue was found when using conda-build on a project that includes cub, since conda-build sets up a cross compilation
enviornment including a find root path.

Remove usage of find_path to locate cub/version.cuh

---

cub/agent/agent_reduce.cuh
cub/block/specializations/block_reduce_warp_reductions.cuh
cub/detail/type_traits.cuh
cub/device/device_reduce.cuh
cub/device/dispatch/dispatch_reduce.cuh
cub/thread/thread_operators.cuh
cub/thread/thread_reduce.cuh
test/test_block_reduce.cu
test/test_block_scan.cu
test/test_device_reduce.cu
test/test_device_reduce_by_key.cu
test/test_device_scan.cu
test/test_device_scan_by_key.cu
test/test_thread_operators.cu
test/test_warp_reduce.cu
test/test_warp_scan.cu

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/428). I also found that we use copy assignment operator on uninitialized memory, which might lead to issues for not primitive types.

P2322R6 accumulator types for reduce

---

cub/agent/agent_reduce_by_key.cuh
cub/agent/agent_scan.cuh
cub/agent/agent_scan_by_key.cuh
cub/agent/single_pass_scan_operators.cuh
cub/block/block_exchange.cuh
cub/block/specializations/block_reduce_warp_reductions.cuh
cub/block/specializations/block_scan_warp_scans.cuh
cub/detail/uninitialized_copy.cuh
cub/device/device_scan.cuh
cub/device/dispatch/dispatch_radix_sort.cuh
cub/device/dispatch/dispatch_reduce.cuh
cub/device/dispatch/dispatch_reduce_by_key.cuh
cub/device/dispatch/dispatch_scan.cuh
cub/device/dispatch/dispatch_scan_by_key.cuh
cub/thread/thread_store.cuh
cub/util_type.cuh
test/test_device_reduce_by_key.cu
test/test_device_scan.cu
test/test_device_scan_by_key.cu

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/428). It's based on the previous [PR](https://github.com/NVIDIA/cub/pull/509) so the first commit might be skipped during this review. 
:warning: Breaking changes:
1. Device scan, scan by key, and reduce by key now do not work with device extended lambdas by default. 
2. `AgentReduceByKey` now accepts accumulator type as the last template parameter.
3. `AgentScan` now accepts accumulator type as last template parameter.
4. `AgentScan::ConsumeRange` now accepts `prefix` as accumulator type instead of output iterator value type.
5. `AgentScanByKey` now accepts accumulator type as the last template parameter.
6. `DeviceReduceByKeyKernel` now accepts accumulator type as the last template parameter.
7. …

P2322R6 accumulator types for scan and reduce by key

---

cmake/CubCudaConfig.cmake
examples/CMakeLists.txt
test/CMakeLists.txt

This works around some failures in Thrust's post-commit CI.
This is due to how `CMAKE_CUDA_FLAGS` works -- all targets in a directory
must share the same flags. Now that some tests always enable RDC to test
CDP launches, we have to disable the tests for non-RDC arches (53, 62, 72).
We can fix this properly once we migrate to using `CMAKE_CUDA_ARCHITECTURES`.
See comments in this patch for details.

Temporarily disable tests for non-RDC architectures.

---

README.md

Addresses the following [issue](https://github.com/NVIDIA/cub/issues/540).

Remove minimal supported version for NVC++

---

cub/device/dispatch/dispatch_radix_sort.cuh
cub/util_device.cuh
test/test_device_radix_sort.cu

Fix `begin_bit == end_bit == 0` for device-wide and segmented sort.

Fix begin_bit == end_bit == 0 for device-wide and segmented sort

---

cub/detail/cpp_compatibility.cuh
cub/device/device_histogram.cuh
cub/device/dispatch/dispatch_histogram.cuh
test/test_device_histogram.cu

The `ScaleTransform` utility precomputes the reciprocal of the "`sample` -> `bin_idx`" scaling factor for floating point types as an optimization.
Trouble is, the `Init` method checked whether `LevelT` is fp while `BinSelect` checked `SampleT`. This caused the optimization to be incorrectly applied when one of these types is fp but the other is not.
Fixed this bug and simplified the implementation of `ScaleTransform` using `cuda::std::common_type` to consistently apply the optimization when either `LevelT` or `ScaleT` are fp.
Fixes #479 and #489 and adds regression tests for both.
- NVIDIA/cub#487: Fixed the `DeviceHistogram::HistogramEven` algorithms when the samples and levels are different types (NVIDIA/cub#479) and when both are integral with fractional bin sizes (NVIDIA/cub#489). …

Fix DeviceHistogram::Even for mixed float/int levels and sample types.

---

cub/detail/type_traits.cuh
cub/detail/uninitialized_copy.cuh
cub/thread/thread_operators.cuh

This PR harmonizes libcu++ namespace usage with the following [PR](https://github.com/NVIDIA/thrust/pull/1763).

Fix libcu++ namespace

---

cub/block/specializations/block_reduce_raking.cuh

The documentation contradicts itself here: BlockReduceRaking seems to support non-commutative operations, but BlockReduceRakingCommutativeOnly doesn't

Fix BlockReduceRaking non-commutative docs

---

cub/detail/uninitialized_copy.cuh

Using copy assignment operator in block exchange triggers different max regcoung between merge sort and block load. This PR disables uninitialized copy optimization to treat the symptom. 
NVBug 3384810

Fix uninitialized copy for NVHPC

---

cub/util_arch.cuh
cub/util_ptx.cuh
cub/warp/specializations/warp_reduce_shfl.cuh
cub/warp/specializations/warp_scan_shfl.cuh

:warning: Deprecated `CUB_USE_COOPERATIVE_GROUPS`
Currently, CUB has code specializations for CTK < 9. Based of the CTK version, we provide a `CUB_USE_COOPERATIVE_GROUPS` macro. If the macro is absent, we disables `*_sync` variants of PTX instructions / intrinsics. This PR removes the macro and all associated code specializations. We don't test that and I have doubts if the following even legal for all the CUB facilities:
```cpp
__device__  __forceinline__ void WARP_SYNC(unsigned int member_mask)
{
#ifdef CUB_USE_COOPERATIVE_GROUPS
__syncwarp(member_mask);
#endif
}
```

Deprecate CTK<9

---

test/test_block_merge_sort.cu

This seems to be some kind of bug, but VS22 considers `stable` to be unused in the block merge sort test.

Fix VS22 build

---

docs/developer_overview.md

This PR briefly explains the current CUB design. The document is intended to help contributors. Coming PTX dispatch changes will lead to changes in this document. Having a diff of design overview will ease the transition period (still having a few PRs in flight that apply existing dispatch logic).

First version of developer overview

---

cub/agent/agent_radix_sort_downsweep.cuh
cub/block/block_radix_rank.cuh
cub/util_ptx.cuh
test/test_block_radix_rank.cu

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/552) by masking inactive threads in match any. The code generation hasn't changed for thread blocks with `(BlockThreads % 32) = 0`.

Fix block radix rank for blocks with non multiple of 32 threads

---

.clang-tidy

This PR adds initial version of clang-tidy file. It's a port of cudf [one](https://github.com/rapidsai/cudf/blob/branch-22.10/cpp/.clang-tidy). I expect it to be further tuned for CUB.

Add initial version of clang-tidy

---

cub/util_namespace.cuh

This PR is an alternative fix of the following [issue](https://github.com/NVIDIA/cub/issues/545). The suggested solution of making all kernels static would explode binary sizes for builds with `-rdc=true`. @jrhemstad suggested an alternative approach where we encode the list of architectures we are compiling against in the CUB namespace. 
This PR introduces inline namespace whose name is generated from combination of `CUB_VERSION` and `__CUDA_ARCH_LIST__`. This solution addresses original issue, since dispatch layer is calling kernels from the same set or architectures it was compiled against. On the other hand, the solution preserves weak linkage when the code compiled with `-rdc=true`. 
Additionally, `CUB_DISABLE_NAMESPACE_MAGIC` macro is provided to disable mentioned changes. Providing …

Fix of CUB linkage

---

test/test_block_load_store.cu
test/test_block_radix_sort.cu
test/test_block_reduce.cu
test/test_device_radix_sort.cu
test/test_device_reduce.cu
test/test_device_reduce_by_key.cu
test/test_device_run_length_encode.cu
test/test_device_scan.cu
test/test_device_scan_by_key.cu
test/test_device_spmv.cu
test/test_iterator.cu
test/test_iterator_deprecated.cu
test/test_util.h
test/test_warp_reduce.cu

There are compilation issues for our tests on some platforms due to `char` usage. According to the standard:
> Type char is a distinct type that has an implementation-defined choice of “signed char” or “unsigned char” as its underlying type.
CUDA vector types add to this confusion by using `char2` as a synonym for `signed char` instead of `char`. Ideally, we'd use `std::int8_t` and `std::uint8_t` here, but I'd like to postpone this refactoring, since the process of replacing primitive types with `std::*` ones in already in progress ([Catch2 PR](https://github.com/NVIDIA/cub/pull/365)). As a quick fix, I use signed char when applicable for now.

Don't use char in tests

---

cub/device/device_merge_sort.cuh
test/test_device_merge_sort.cu

CUB has a  `SortKeysCopy` and a `StableSortKeys`. This PR adds `StableSortKeysCopy` so a sort in-place is not required. The in-place `StableSortKeys`  requires a temporary vector if a copy is needed.
Since `StableSortKeys` calls `SortKeys` and `SortKeysCopy` uses the same kernels as `SortKeys` (which appear to already be stable-sort enabled), the new `StableSortKeysCopy` simply calls `SortKeysCopy`.

Add DeviceMergeSort::StableSortKeysCopy API

---

cub/util_namespace.cuh

Cherry-pick https://github.com/NVIDIA/cub/pull/547 for 2.0.X branch.

Backport CUB linkage fix into 2.0

---

cub/block/block_radix_rank.cuh

Mask of all ones in `SHFL_IDX_SYNC` in block radix rank.

Mask of all ones in `SHFL_IDX_SYNC` in block radix rank

---

cmake/CubBuildCompilerTargets.cmake
cub/agent/agent_histogram.cuh
cub/agent/agent_select_if.cuh
cub/block/block_exchange.cuh
cub/device/dispatch/dispatch_radix_sort.cuh

This PR fixes reordering in member initializer lists. Since `-Wall` was added to host compiler, kernels were not covered. Specifying `-Wreorder` directly led to having those reordering visible.

Fix reordering in CUB member initializer lists

---

.clangd
cub/detail/detect_cuda_runtime.cuh

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/522). It's now possible to disable CDP support while building with RDC. To do so, it's sufficient to define `CUB_DISABLE_CDP` macro before including any of the CUB headers. 
Also adopted clangd helper from stdexec.

Add option to opt out CDP

---

cub/device/device_reduce.cuh
test/test_device_reduce.cu

This PR partially addresses the following [issue](https://github.com/NVIDIA/cub/issues/584). Supporting larger offsets for `ArgMin` and `ArgMax` would have to wait, since it's a bit more involving. There also could be a bit better testing, but it might wait till Catch2 rewrite. 
The main purpose of this PR is to unblock original issue by providing an example of what we expect from such a change. The main direction of this modification can be found [here](https://github.com/NVIDIA/cub/issues/212).

Support reduction for more than 2^31 items

---

cub/agent/agent_sub_warp_merge_sort.cuh
test/test_device_segmented_sort.cu

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/594) and enables `bool` as key type in the new device segmented sort. The issue happens only for small segments since that's what is triggering merge sort to be used. Merge sort relies on comparison and we end up comparing `true` or `false` with `oob = 0xFF`. Initially, I was trying to `Traits<KeyT>::TwiddleIn(key)` once before sorting and `Traits<KeyT>::TwiddleOut(key)` after sorting so as to get consistency with what radix counterpart is doing. Although this simplifies the code (no need to treat `__half` etc.), this also introduces noticeable slowdown (4%) into sorting of small segments on signed key types. The slowdown disappears only on `std::int64_t`. So, instead we change the way `oob` is computed. This …

Fix seg sort for bool keys

---

cub/device/dispatch/dispatch_reduce.cuh

When there are more than one tile of input items, we launch two kernels for reduction. During the second kernel launch, we accumulate partial aggregates from thread blocks. In this case, `int reduce_grid_size` is passed to `OffsetT num_items` kernel parameter. Thrust `triple_chevron` is not type safe when used on device. These facts lead to a mismatch of data size we put into a param buffer (4 bytes) and that the kernel reads from the buffer (8 bytes). This seems to be a bug that was long present in thrust, that uses dispatch layer directly with offset types different from `int32_t`. In the case of host-side usage, type conversion takes place, leading to normal execution.

Fix device-side reduce launch with large inputs

---

cub/agent/agent_reduce_by_key.cuh
test/test_device_run_length_encode.cu

This is a suggestion to fix #596.
The root cause is in `cub/agent/agent_reduce_by_key.cuh`, where, for the very first tile of items, we're using `keys[0]` as the `tile_predecessor` that is later fed into the `BlockDiscontinuity`:
```
tile_predecessor = (tile_idx == 0) ? keys[0] : d_keys_in[tile_offset - 1];
...
BlockDiscontinuityKeys(temp_storage.scan_storage.discontinuity)
.FlagHeads(head_flags, keys, prev_keys, flag_op, tile_predecessor);
```
Since `NaN == NaN` is false: if `keys[0]` is `NaN`, `BlockDiscontinuityKeys` evaluates `tile_predecessor == keys[0]` as false and will flag `keys[0]` as the beginning of a new run.
After having run `BlockDiscontinuity`, we reset the flag on the very first item.
```
if (threadIdx.x == 0 && tile_idx == 0)
{
scan_items[0].key = 0;
}
```
An alternative …

Fix RLE when items[0] is NaN

---

README.md
cmake/CubCudaConfig.cmake
cub/detail/detect_cuda_runtime.cuh
cub/detail/device_synchronize.cuh
cub/util_device.cuh

Brings in changes that were released as part of CTK 12.

Ctk12 sync

---

cub/util_ptx.cuh
cub/util_type.cuh
test/catch2_test_printing.cu
test/test_block_radix_rank.cu
test/test_device_batch_memcpy.cu
test/test_device_radix_sort.cu
test/test_util.h

This PR supports `__int128_t` and `__uint128_t` in block/device radix sort as well as block radix rank. It's partially answering the [question](https://github.com/NVIDIA/cub/issues/52) on 128 bit types support. Performance wise, `__int128_t` utilize BW similarly to 64 bit types.

Support __{u,}int128_t in radix sort

---

cub/thread/thread_operators.cuh
cub/util_device.cuh
cub/util_macro.cuh

This PR provides a small cleanup and replaces custom implementations of `Equality`, `Inequality`, `Sum`, `Difference`, and `Division` with libcu++ ones for C++14+. Once C++11 support is dropped, we'll remove custom implementations completely.

Use libcu++ function objects

---

cub/warp/warp_scan.cuh
test/test_warp_scan.cu

Fix warp scan exlusive sum for vector types

---

test/CMakeLists.txt
test/c2h/generators.cu

I've missed linking Catch2 helper with Thrust specified during CMake configuration step. This led to different Thrust version being used by generator and the tests.

Avoid system thrust usage in tests

---

.clangd
cub/agent/single_pass_scan_operators.cuh
cub/detail/strong_load.cuh
cub/detail/strong_store.cuh

Decoupled Look-Back is a core of many CUB algorithms. This PR provides a few optimizations that help reduce contention on L2 and improve overall performance. This PR is intended as the first in a series of optimizations/tunings, so selecting the best parameters is out of the scope for now. This PR also addresses the following [issue](https://github.com/NVIDIA/cub/issues/591) by relying on strong operations (`.relaxed`, `.release` etc.) instead of hints (`.cg`).
- Introduce a larger delay before loading the first look-back window since the data has a low probability of being updated. 
- Try loading tile states before falling into the spin loop. Once the first window is in the partial state, the previous ones should likely be as well. In other words, there's no point in waiting before …

Optimize Decoupled Look-Back

---

cub/agent/agent_batch_memcpy.cuh
cub/util_ptx.cuh
test/test_device_batch_memcpy.cu

This PR fixes an issue that exists in `DeviceMemcpy::Batched` for pre-Volta architectures. The root cause of this issue is the `BitPackedCounter` component, which previously exhibited undefined behaviour when its counters were backed by more than a single `uint32` data member. 
For pre-Volta architectures, we are allocating a power of two number of bits for each counter (specifically, 16 bits to store values `[0, 512]`). Since we needed three counters (each 16 bits), we needed two `uint32` data members, which lead to UB. 
This PR also adds test for the `BitPackedCounter` class.

Fixes DeviceMemcpy::Batched for Pre-Volta Architectures

---

cmake/CubHeaderTesting.cmake
cub/util_type.cuh
examples/CMakeLists.txt
test/CMakeLists.txt
test/test_device_histogram.cu
test/test_device_radix_sort.cu
test/test_device_reduce.cu
test/test_device_segmented_sort.cu

This PR fixes the int128 usage for CTK < 11.5 and also cleans up a few outdated checks (CTK < 11.0).

Cleanup CTK version checks

---

cub/block/block_radix_rank.cuh

Users are trying to [use](https://github.com/NVIDIA/cub/issues/644#issuecomment-1461531350) block radix with more than `65536` keys. Unfortunately this compiles with no clear diagnostic. This PR introduces a compile time error in case tile size is larger than what's supported by our internal counters.

Assert max tile size for radix sort

---

cub/device/device_histogram.cuh
cub/device/dispatch/dispatch_histogram.cuh
test/test_device_histogram.cu

This PR addresses issue https://github.com/NVIDIA/cub/issues/619. 
**The issue**
The root cause is our accurate bin computation for integral types, where the product `(sample - min_level) * scale.fraction.bins` may overflow in certain circumstances.
```
return static_cast<int>(((sample - min_level) * scale.fraction.bins) /
scale.fraction.range);
```
**The following changes are made:**
When computing histogram over integral types, we perform the bin computation using 32-bit integer arithmetic if both operands each comprise at most two bytes. We use 128-bit integer arithmetic if the common type of samples is a 128-bit type. We use arithmetic on 64-bit types otherwise. If the product `(max_level - min_level) * scale.fraction.bins` would overflow for the used arithmetic type, we return …

Fixes overflows for [Multi]HistogramEven over integral types

---

.gitignore
cub/device/device_reduce.cuh
cub/device/device_segmented_reduce.cuh
cub/device/dispatch/dispatch_reduce.cuh
test/test_device_reduce.cu

This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/642) related to properly handling `inf` values by `cub::DeviceReduce::Arg{Max,Min}`.

Fix `cub::DeviceReduce::Arg{Max,Min}` for `inf` values

---

cmake/CubCudaConfig.cmake

This only affects the test suite, examples, etc, and will not affect consumers of CUB.
We haven't supported building CUB's test suite as a standalone project for a while, preferring to build Thrust/CUB tests together.
This change prevents CUB from being successful configuring its test suite unless it is inside the Thrust project.
The arch flags in both projectss will be removed soon and replaced with the standard CUDA_ARCHITECTURE CMake properties during the switch to a Thrust/CUB/libcu++ monorepo. This error will be removed when that work is completed.

Force reuse of CUDA arches from thrust.

---

cub/host/mutex.cuh
cub/util_allocator.cuh
test/test_device_scan.cu
test/test_device_scan_by_key.cu
test/test_device_spmv.cu

We currently provide `cub::Mutex` as part of our public API. The facility is using `std::mutex` internally for C++11 and forward. Since the facility is not tested and doesn't provide any extra functionality, I'm deprecating it and suggesting users to rely on `std::mutex` instead. Marking this as a breaking change not to forget to mention this in release notes. 
This PR also fixes some narrowing conversions in our tests.

Deprecate cub::mutex and fix remaining narrowing conversions in tests

---

test/CMakeLists.txt
test/c2h/generators.cu
test/catch2_test_cdp_helper.h
test/catch2_test_cdp_wrapper.cu

This PR provides CDP wrappers that can ease porting device-scope API tests to Catch2. These wrappers allow us not to reimplement CDP dispatch logic in every test. PR also contains a fix for custom types data generator.

CDP abstraction for CUB tests

---

cub/block/block_merge_sort.cuh

This PR addresses regression (more than 45%) of merge sort used with relatively complex comparison operators. The regression is caused by high-level unroll pragma that didn't lead to unrolling the loop before CTK 11.8. With a newer version of CTK, the pragma took effect and led to kernel size explosion. Removing this pragma has little impact on the sorting of fundamental types.

Optimize merge sort

---

cub/block/specializations/block_scan_raking.cuh

We've recently started fixing writes into uninitialized memory in CUB algorithms. Currently, the tests that should check if CUB scan is using uninitialized memory is failing on Kepler GPUs, because those are using `BLOCK_SCAN_RAKING`. This PR fixes uninitialized writes by `BLOCK_SCAN_RAKING`.

Fix uninitialized copy in block scan raking

---

cub/util_type.cuh
test/catch2_test_util_type.cu

Currently `cub::detail::non_void_value_t<void*, my_fallback_type>` fails to compile with the error message `reference to void is not allowed` due to instantiating the `iterator_traits` template with a reference to void member type.
This PR fixes the compilation error.
Thanks to @senior-zero for helping to iterate on the fix.

Fixes non_void_value_t for ptr-to-void iterator types

---

test/catch2_test_warp_reduce.cu

Before migrating the WarpReduce tests to Catch2, our tests for generic reduction were limited to builtin types. This PR reverts some of the additional coverage introduced with the Catch2 migration of these tests.

Limits tests for generic WarpReduce tests to builtin types

---

test/test_device_batch_copy.cu

This PR removes unused variables in `DeviceCopy::Batched`

Removes unused variables in DeviceCopy::Batched

---

test/test_device_batch_copy.cu

To fix the following warning:
```
thrust/thrust/cmake/../..\thrust/detail/vector_base.inl(233): warning C4244: 'argument': conversion from 'int' to 'const char', possible loss of data 
...
thrust/thrust/cmake/../..\thrust/detail/vector_base.inl(233): warning C4244: 'argument': conversion from 'int' to 'const char', possible loss of data 
```

Fixes narrowing conversion warning in tests

---

benchmarks/scripts/analyze.py
cub/device/dispatch/dispatch_scan.cuh
cub/thread/thread_operators.cuh

Sum tuning converges on the following speedups:
| I8 | I16 | I32 | I64 | I128 | F32 | F64 |
| --: | ----: | ---: | ---: | ---: |  ---: |  ---: | 
| -17% | -4% | -6% | -12% | -60% | -17% | -12% |  
<details>
|  T      |  Elements      |   Cmp Noise |         Diff |   %Diff |
|--------:|---------------:|------------:|-------------:|--------:|
|   I8    |      2^16      |       1.77% |    -0.257 us |  -2.64% |
|   I8    |      2^20      |       1.75% |     0.111 us |   0.89% |
|   I8    |      2^24      |       1.58% |    -4.403 us |  -9.64% |
|   I8    |      2^28      |       0.46% |   -98.185 us | -16.66% |
|   I16   |      2^16      |       2.16% |    -0.109 us |  -1.05% |
|   I16   |      2^20      |       1.70% |    -0.050 us |  -0.38% |
|   I16   |      2^24      |       2.23% | …

Introduce SM90 tuning policy into scan

---

cub/agent/single_pass_scan_operators.cuh

Last week's [PR](https://github.com/NVIDIA/cub/pull/710) introduced a regression for direct users of `ReduceByKeyScanTileState` on pre-Volta architectures. Delay should contain thread fence in pre-Volta cases in order to prevent hoisting.

Fix reduce by key tile state for Pascal

---

cub/warp/warp_exchange.cuh
cub/warp/warp_load.cuh
cub/warp/warp_merge_sort.cuh
cub/warp/warp_reduce.cuh
cub/warp/warp_scan.cuh
cub/warp/warp_store.cuh
docs/index.rst
docs/repo.toml

This PR addresses https://github.com/NVIDIA/cub/issues/677 and modernizes the docs to use rst.

Improve docs for warp-wide primitives
