- cub/util_arch.cuh
> Stop using macro which is deprecated in cuda9

- cub/device/dispatch/dispatch_radix_sort.cuh
- cub/util_ptx.cuh
- volta sorting policy
- remove LOP3 from match sorting
> volta updates

- cub/util_cpp_dialect.cuh
> Update deprecation messages for CTK 11.4.

- CHANGELOG.md
- README.md
Preparing for 1.13.0-rc0.
Tagging contributors mentioned in the release notes -- let me know if you'd like to use a different name in the changelog, I just pulled names from Github for now. Let me know by 6/23 so I can update in time for the final release.
@canonizer
@elstehle
@himanshu007-creator
@lilohuang
@mnicely
@nv-dlasalle
@peter9606
@psvvsp
@rukshan99
@zasdfgbnm
> Update changelog and readme for the 1.13.0 release.

- cub/detail/device_synchronize.cuh
- cub/util_device.cuh
> Add wrapper around cudaDeviceSynchronize that supports CDP joins.

- test/test_block_radix_sort.cu
> Update incorrect comments in test_block_radix_sort.

- CHANGELOG.md
- README.md
Pinging contributors for the 1.16.0 release.
I'm merging this now to tag the RC ASAP, but if there are any changes you'd like to make to the changelog notes, let me know by the end of the week. The final release is planned for Monday 2/14.
- @canonizer
- @robertmaynard
- @senior-zero 
- @zasdfgbnm
> Update CHANGELOG.md and README.md for 1.16.0.

- cub/agent/agent_select_if.cuh
- cub/device/dispatch/dispatch_three_way_partition.cuh
- cub/device/dispatch/dispatch_unique_by_key.cuh
- test/test_device_select_if.cu
This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/235).
> Normalize flags in select flagged

- cub/thread/thread_operators.cuh
If second.value isn't copied into a temporary in this location, nvc++ will crash while compiling the `TestScanByKeyWithLargeTypes` test in `thrust/testing/scan_by_key.cu`.
Bug requires NVIDIA/thrust#1555 to repro.
> WAR nvc++ bug:

- CHANGELOG.md
- README.md
I'll merge this in a moment before I tag the RC, but if anyone spots an issue in the changelog let me know before the final release date (5/23).
Contributors:
@canonizer
@karthikeyann
@kshitij12345
@robertmaynard
@senior-zero
> Update changelog for 1.17.0.

- cub/device/dispatch/dispatch_adjacent_difference.cuh
This PR allows `__device__` extended lambdas usage in the device adjacent difference (nvbug 3641330). The issue was caused by `invoke_result_t` usage on `__device__` extended lambda on the host side.
> Allow device lambdas in device adjacent difference

- cub/block/block_adjacent_difference.cuh
> Add missing colon in cub::BlockAdjacentDifference::FlagTails

- cub/warp/warp_merge_sort.cuh
This PR addresses the following [issue](https://github.com/NVIDIA/cub/issues/517).
> Fix warp merge sort docs

- cub/agent/agent_adjacent_difference.cuh
- cub/block/block_adjacent_difference.cuh
- cub/device/dispatch/dispatch_adjacent_difference.cuh
- test/test_block_adjacent_difference.cu
- test/test_device_adjacent_difference.cu
This is a backport of the following [PR](https://github.com/NVIDIA/cub/pull/508)
> Backport adjacent difference fixes

- cub/util_namespace.cuh
Cherry-pick https://github.com/NVIDIA/cub/pull/547 for 1.17.X branch
> Use inline namespace

- test/test_warp_scan.cu
Warp scan is not expected to be used with non-power-of-two logic warp sizes when there's more than one logic warp per hardware warp. Our test happened to be relying on that. This PR fixes warp scan test not to launch more threads than warp reduce expects.
> Fix warp scan test

- cub/device/dispatch/dispatch_radix_sort.cuh
Onesweep sorting policy for H100.
> Sorting policy for H100

- cmake/CubCudaConfig.cmake
- cmake/CubUtilities.cmake
- cub/device/dispatch/dispatch_batch_memcpy.cuh
- cub/warp/specializations/warp_reduce_shfl.cuh
- test/CMakeLists.txt
- test/c2h/custom_type.cuh
- test/c2h/generators.cuh
- test/catch2_test_printing.cu
This PR fixes a few issues that affect Clang CUDA and allows one to build CUB tests with it.
> Fix Clang CUDA

- test/test_device_reduce.cu
This PR adds device reduce tests for `__half` and `__nv_bfloat16`.
> Test reduction with bf16 and fp16

- cmake/CubHeaderTesting.cmake
- examples/CMakeLists.txt
- test/CMakeLists.txt
This change corresponds to the following [PR](https://github.com/NVIDIA/thrust/pull/1874). This PR has to be merged first.
> Fix clang / nvcc CI build

- CHANGELOG.md
- cub/util_type.cuh
- cub/version.cuh
- test/test_device_histogram.cu
- test/test_device_radix_sort.cu
- test/test_device_reduce.cu
- test/test_device_segmented_sort.cu
Updates the changelog, syncs main with 2.1.x, bumps the version on main to 2.2.0.
> 2.1.x changelog update

- test/test_device_radix_sort.cu
In some cases, radix sort tests do not fit into RAM. This PR reduces RAM footprint by comparing arrays on GPU instead of CPU. This change leads to about 20% test speedup and saves about 10GB of RAM.
> Reduce RAM usage by radix sort tests

- cub/device/dispatch/dispatch_spmv_orig.cuh
Some inputs are leading to out-of-bounds accesses in `cub::DeviceSpmv`. For instance, if the matrix has many rows and columns but not a single non-zero element, we'll try to access `num_nonzeros - 1`. This PR addresses this issue by short-circuiting into a kernel that fills `y` with `ValueT{0.0}`, which is used a accumulator initializer in other parts of `cub::DeviceSpmv`.
> Fix `cub::DeviceSpmv` for empty matrices

- cmake/CubBuildCompilerTargets.cmake
- cub/agent/agent_histogram.cuh
- cub/agent/agent_select_if.cuh
- cub/block/block_exchange.cuh
- cub/device/dispatch/dispatch_radix_sort.cuh
> Backport fixes for reordering in CUB member initializer lists into 2.0 branch

- cub/agent/single_pass_scan_operators.cuh
- examples/device/example_device_decoupled_look_back.cu
- test/catch2_test_device_decoupled_look_back.cu
Addresses https://github.com/NVIDIA/cub/issues/699
> Decoupled look-back example

- test/catch2_test_cdp_helper.h
Compilation with CTK 11.5 is currently broken for CDP wrapper. Anonymous namespaces seems to be causing the issue. This PR achieves internal linkage by using different wrapper names + static functions instead of anonymous namespaces.
> Fix CDP test wrapper for CTK 11.5

- benchmarks/bench/run_length_encode/encode.cu
- cub/device/device_run_length_encode.cuh
- cub/device/dispatch/dispatch_rle.cuh
- cub/device/dispatch/tuning/tuning_run_length_encode.cuh
| MaxSegSize |  I8  |  I16 |  I32 |  I64 | I128 |  F32 |  F64 |
| ---------- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
|      2     | -26% | -22% | -16% |  -4% |  -8% | -24% |  -3% |
|     16     | -38% | -37% | -37% | -23% | -24% | -27% | -21% |
|    256     | -38% | -36% | -35% | -20% | -22% | -25% | -18% |
<details>
|  T{ct}  |  OffsetT{ct}  |  Elements{io}  |  MaxSegSize  |   Cmp Noise |   %Diff |
|---------|---------------|----------------|--------------|-------------|---------|
|   I8    |      I32      |      2^16      |     2^1      |       1.42% |   1.15% |
|   I8    |      I32      |      2^20      |     2^1      |       1.81% |  -3.10% |
|   I8    |      I32      |      2^24      |     2^1      |       1.27% | -22.74% |
|   I8    |      I32      |      2^28      | …
> Tune RLE for SM90
